- input/assets/css/override.less
- Signals to the user which section of the site they are currently in.
- Fixes #16
- (note this change is unrelated to the points I made on the issue)
> Add active border to link of section user is in

- input/docs/handbook/snippets/index.md
A section explaining the snippets added in [#1444 in the ReactiveUI repo](https://github.com/reactiveui/ReactiveUI/pull/1444)
> Add section about snippets to docs

- input/docs/handbook/snippets/index.md
Forgot to add this in the previous PR.
Makes it easier for users unfamiliar with snippets to start using them.
> Add install instructions for snippets

- input/docs/handbook/commands/binding-commands.md
This is to prevent multiple event subscriptions when using the overload of `BindCommand` with the `toEvent` parameter and passing an event name.
This is related to [PR #1484 in the ReactveUI repo](https://github.com/reactiveui/ReactiveUI/pull/1484)
> Add notice about disposing command-to-event bindings

- input/docs/getting-started/installation/nuget-packages/index.md
- input/docs/getting-started/installation/setting-up-a-new-project.md
- input/docs/handbook/data-binding/windows-presentation-foundation.md
Fixed references to WPF as "Windows Presentation **Framework**" instead of "Windows Presentation **Foundation**".
> Fixed wrong meaning of WPF

- input/_Footer.cshtml
Redirecting to `stack-overflow` instead of `stackoverflow` as defined in /input/_redirects
> Fix incorrect StackOverflow url in footer

- input/sponsorship/index.cshtml
- input/sponsorship/index.md
These aren't used because of the redirect from /sponsorship to /support and are creating a build warning because the two files end up at the same place.
> Remove unused sponsorship files

- input/assets/css/override.less
- general reformat to be consistent
- remove some commented out styling, if we want it back there's always git history
- made the "hover" state of top level nav links match the "active" styling for consistency
> styling: tidy stylesheets and make link hover match active for main nav

- input/docs/samples/index.md
The original link redirects to the updated URL here.
> Fix Xamarin.Forms sample link

- input/index.cshtml
https://reactiveui.net/License page doesn't exist,
but https://reactiveui.net/license works.
> Fix license link

- input/index.cshtml
Removed large space in front of the main page. It seemed rather odd to me that it was there, maybe without it the website would look more elegant!
Before:
After:
> Reduce empty space on main page

- input/about/index.html
Noticed the Reactive Extensions link to .Net Foundation page gives a 404. Found the correct url on .Net Foundation site for Reactive Extensions for .NET and fixed it.
> Fixed broken url link to Reactive Extensions site

- input/docs/getting-started/index.md
Tried making <a href="https://reactiveui.net/docs/getting-started/">Getting Started</a> page more informative -- added quick links to useful documentation pages, videos, samples, packages. Also used .NET Core code of conduct.
> Improve getting started page

- .vsts-ci.yml
- build.cake
- tools/packages.config
Resolves #143 
- v0.21.1 doesn't allow for versioning of cake dependencies
> Bump Cake to v0.29.0

- .gitignore
- build.cake
This PR updates the site to Wyam 1.5.0. I was expecting some trouble [based on this comment](https://github.com/reactiveui/website/issues/151#issuecomment-413901595) but the process was totally straightforward. It's possible that an intermediate version caused problems that 1.5.0 has now resolved.
Wyam did spit out some warnings about duplicate paths, but that doesn't look any different than the current site - there are a few open Wyam issues for API path resolution that might help with that in the future.
> Updating to Wyam 1.5.0

- input/docs/handbook/dependency-inversion/custom-dependency-inversion.md
> Added custom-dependency-inversion.md (#161)

- input/docs/handbook/view-models/index.md
We actually need to go back `../` to the `handbook` instead of looking for pages in `./`
> Fix broken links on ViewModels page

- input/assets/css/override.less
We can create en expander control in the .MD markup, but usually we don't use this feature, as expanders don't look great, see an example:
Tried to improve this control so now it looks nice and we can use it.
This may help providing a great <a href="https://github.com/reactiveui/website/pull/171">getting started</a> guide.
> Make expander control look great

- input/assets/css/override.less
When I view the website via a mobile phone with a narrow screen, I can barely read the code:
This option is better (with horizontal scroll bar enabled in code snippets, so lines won't wrap):
> Don't wrap long lines of code

- input/assets/css/override.less
ReactiveUI syntax highlighting theme used to be dark:
https://files.slack.com/files-pri/T02AG6QJM-FCKM4E4NM/image.png
Let's update it using colors from ReactiveUI and ReactiveExtensions logos:
https://files.slack.com/files-pri/T02AG6QJM-FCMJUPXLN/image.png
> Update syntax highlighting theme

- input/assets/css/override.less
> Many people with cognitive disabilities have trouble tracking lines of text when a block of text is single spaced. Providing spacing between 1.5 to 2 allows them to start a new line more easily once they have finished the previous one. 
See <a href="https://www.w3.org/TR/WCAG20-TECHS/C21.html">W3C C21: Specifying line spacing in CSS</a>
> Line spacing (leading) is at least space-and-a-half within paragraphs, and paragraph spacing is at least 1.5 times larger than the line spacing. 
See <a href="https://www.w3.org/TR/2008/REC-WCAG20-20081211/#visual-audio-contrast-visual-presentation">W3C Web Content Accessibility Guidelines (WCAG) 2.0</a>
> Increase text line height

- input/docs/handbook/when-activated/index.md
We should mention `DisposeWith` when we are talking about memory leaks. I've seen a little misunderstanding in the <a href="https://reactivex.slack.com">Slack channel</a> so decided to clarify this :)
> Mention DisposeWith on WhenActivated page

- input/docs/getting-started/installation/xamarin-forms.md
The package name is actually `ReactiveUI.Events.XamForms`, not `ReactiveUI.Event.XamForms`. https://reactiveui.net/docs/getting-started/installation/xamarin-forms
> Fix Events typo

- input/assets/css/override.less
We have a main page that looks like this:
Look at the "Declarative, composable code!" code example. 
It looks nice and uses the same colors the website theme uses.
With this tweak, other code snippets will also look like the one on the main page:
Not that important, but I think this looks better.
> Improve code highlighter colors

- input/docs/handbook/data-binding/xamarin-forms.md
Sometimes it is not so trivial to declare a control from a custom assembly with generic type parameters. Worth mentioning.
> Mention clr-namespace syntax

- input/blog/2018-11-11-reactiveui-v9.2.2-released.md
If you try clicking "here" on [this page](https://reactiveui.net/blog/2018/11/reactiveui-v9.2.2-released), you'll see a 404 screen.
> Fix broken link

- input/docs/handbook/routing/index.md
Addresses https://github.com/reactiveui/website/issues/212
> Improve ReactiveUI Routing docs

- input/docs/resources/samples.md
@glennawatson made [an app covering almost all ReactiveUI features](https://github.com/glennawatson/ReactiveGit). I've learned a lot while reading it's source code. Wondering why isn't it on the samples page yet :) Thank you Glenn for such a great open-source app. 
Also I deliberately removed the "FirstStepsRUI" app because it's outdated and no longer maintained.
> Add ReactiveGit WPF sample app

- input/docs/guidelines/framework/command-names.md
- input/docs/guidelines/framework/commands.md
Removed `CreateAsyncObservable` method from docs. That method no longer exists and can confuse users.
> Use proper CreateFrom* method

- input/docs/handbook/data-persistence/index.md
It appears that the popular `Newtonsoft.Json` library actually supports `[DataContract]` attributes, so let's mention this instead of recommending writing tightly coupled code (my bad) https://www.newtonsoft.com/json/help/html/DataContractAndDataMember.htm
> Don't say Newtonsoft doesn't support DataContract

- input/assets/css/override.less
They handle font scaling differently than Windows. Before:
After:
> Hide horizontal scrollbar on Ubuntu

- input/_Footer.cshtml
Currently there is no link to ReactiveUI twitter on the main page. Fixed that.
> Add Twitter link

- input/docs/guidelines/platform/windows-forms.md
- input/docs/guidelines/platform/windows-presentation-framework.md
- input/docs/guidelines/platform/windows-universal-platform.md
- input/docs/guidelines/platform/xamarin-android.md
- input/docs/guidelines/platform/xamarin-forms.md
- input/docs/guidelines/platform/xamarin-ios.md
- input/docs/guidelines/platform/xamarin-mac.md
- input/docs/handbook/data-binding/avalonia.md
Resolves https://github.com/reactiveui/website/issues/276 and https://github.com/reactiveui/website/issues/288 (a bit)
> Fix broken links, document Avalonia type-safe bindings usage

- input/docs/getting-started/installation/index.md
Accidentally came across a blog post about [unlisted ReactiveUI packages](https://reactiveui.net/blog/2018/05/delisting-of-versions-before-8-0-0-from-nuget) while googling some stuff. I think referencing that post from the Installation guide will be a wise decision, I've seen folks complaining they can't use ReactiveUI with legacy .NET implementations which they have to use at work. But that's possible indeed. For example, I was unable to use ReactiveUI v8+ when developing stuff for  Lumia devices and Surface Hubs, but v8-alpha works good on those platforms.
> Mention unlisted packages blog post

- input/assets/css/override.less
UI hotfix.
On narrow screens we get the following behavior (one more tab has been added recently):
Nothing.
> Fix too large nav bar splitting into two lines

- input/_redirects
docs update
This page https://reactiveui.net/docs/handbook/commands/ says:
**Note** For performance based solutions you can also use the nameof() operator override of ToProperty() which won't use the Expression. Read more on ObservableAsPropertyHelper here.
The "here" link directs to "https://reactiveui.net/docs/handbook/oaph", which doesn't exist.
Need to change to /docs/handbook/observable-as-property-helper/
-
- [+] Tests for the changes have been added (for bug fixes / features)
- [+] Docs have been added / updated (for bug fixes / features)
> /docs/handbook/oaph --> observable-as-property-helper

- input/docs/guidelines/debugging/enable-framework-logging.md
Simplifying LoggingService will make the code more readable, short and remove unnecessary extra comparison of logLevel local value and casting it to int. This may also make code more performant in a heavy-load scenario.
docs update
too much code
just the code we need
nothing, cause it's the docs
- [+] Tests for the changes have been added (for bug fixes / features)
- [+] Docs have been added / updated (for bug fixes / features)
> simplify LoggingService and ConfigureLogging()

- input/_redirects
Resolve https://github.com/reactiveui/ReactiveUI/issues/2053 for older ReactiveUI packages.
The Installation page has moved and the existing links to it [got broken](https://github.com/reactiveui/ReactiveUI/issues/2053).
Now folks will get redirected to the new [Installation page location](https://reactiveui.net/docs/getting-started/installation/).
Nothing.
> Redirect to the new Installation page location

- input/docs/reactive-programming/index.md
Should we use the .NET docs for Observer Design Pattern?
Link switch for "Observer Design Pattern", link reader to the .NET docs of the subject instead of just Wikipedia page.
_Observer Design Pattern_ links to [the subject on Wikipedia](https://en.wikipedia.org/wiki/Observer_pattern).
_Observer Design Pattern_ links to [the subject in MSDN docs](https://docs.microsoft.com/en-us/dotnet/standard/events/observer-design-pattern).
Nothing. It's just a single link update.
> .NET docs instead of Wikipedia

- input/docs/handbook/data-persistence/index.md
Updates [Data Persistence](https://reactiveui.net/docs/handbook/data-persistence/) documentation page.
`RxApp.SuspensionHost` isn't properly documented at this point IMHO, let's fix :)
Nothing.
> Update Data Persistence docs

- input/docs/guidelines/framework/dispose-your-subscriptions.md
The old version of the link responds with 404.
Also changed the code snippet to enable syntax highlighting.
Documentation update.
Old link responds with 404.
Link with documentation opens normally.
Nothing.
> Fixed a dead link and updated code snippet.

- input/docs/handbook/when-activated/index.md
As of 10.0.1 ISupportsActivation has been renamed to IActivatableViewModel.  I've adjusted the documentation to reflect this.
Docs update.
The documentation currently references the old `ISupportsActivation` interface.
The documentation will reference the new `ISupportsActivation` interface,
The documentation for anyone who hasn't upgraded to version 10.0.1.
> Update WhenActivated documentation.

- input/docs/handbook/dependency-inversion/custom-dependency-inversion.md
See: https://github.com/reactiveui/splat/pull/380
Just improved the registration bit to use our dedicated ex. methods instead of user instantiating the resolver on their own.
> Updated initialization external DI code

- input/docs/getting-started/index.md
- On .NET Core 3.0 on Windows you will get a Win32Exception when you try to open any URL, because of this https://github.com/dotnet/corefx/issues/10361
```
System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
at System.Diagnostics.Process.Start()
at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
at System.Diagnostics.Process.Start(String fileName)
at ReactiveDemo.NugetDetailsViewModel.<.ctor>b__2_0() in C:\temp\ReactiveDemo\ReactiveDemo\ReactiveDemo\NugetDetailsViewModel.cs:line 22
at ReactiveUI.ReactiveCommand.<>c__DisplayClass0_0.<Create>b__1(IObserver`1 observer) in d:\a\1\s\src\ReactiveUI\ReactiveCommand\ReactiveCommand.cs:line 108
at …
```
> Fix Win32Exception on .NET Core on Windows

- input/docs/handbook/dependency-inversion/index.md
Since the common name for this pattern is Service _locator_ (the implementation file is also called `Locator` though - https://github.com/reactiveui/splat/blob/master/src/Splat/ServiceLocation/Locator.cs), so I think renaming it to this will reduce confusion by a bit (I was initially confused by the naming...). 
_Note that I didn't change the wordings in the original quote from Anaïs Betts._
> Use Service "Locator" instead of Service "Location"

- input/docs/guidelines/framework/asynchronous-commands.md
This wanted to denote plural here, not possession, but also if we denote plural, then we would need to denote plural in the following "`ReactiveCommand`", too. I think removing the pluralization altogether avoids the awkward "s" after the codeblock.
> Remove possession

- input/docs/handbook/data-binding/windows-store.md
will all the current libraries and frameworks, with out the `this` in front of `RaiseAndSetIfChanged(ref theText, value):` I had a compiler error that my TheViewModel did not have matching signature.
I noticed all the other examples included the `this.` so I added it here and it worked.
not that I'm aware of
To be honest I'm not totally sure why the `this` is required. In fact it kinda bugs me that it is required to compile.  As I understand inheritance the `this` shouldn't be required.  But since who ever made up the documentation for the other frameworks had explicitly included it, and since that change allowed the compilation to work, I figured it wouldn't hurt …
> Added the this. to TheText setter

- input/docs/handbook/scheduling/index.md
> Fix invalid syntax for scheduling

- input/docs/getting-started/index.md
Replaced deprecated package "NuGet.Protocol.Core.v3" with actual "NuGet.Protocol" and removed "NuGet.Client" as it is not needed in this example.
> Replace deprecated packages with actual one

- input/docs/handbook/observable-as-property-helper/index.md
`ToProperty() is exposed as an ExtensionMethod on IObservable<T>`
and 
`ToProperty is an extension method on IObservable<T> and semantically acts like a "Subscribe".`
were both in the OAPH docs, removed the first
> remove minor duplicate in OAPH docs

- input/docs/getting-started/compelling-example.md
Remove all less and greater than signs (`<`, `>`) around http-links in code.
Invalid syntax doesn't compile.
> Remove greater and less than signs around links

- input/docs/handbook/testing/index.md
closes #416
replaces 404 link to https://reactiveui.net/api/reactiveui.testing/testutils with https://reactiveui.net/api/reactiveui.testing/
> #416 point to reactiveui.testing instead of testutils

- input/docs/handbook/data-binding/index.md
- input/docs/handbook/data-binding/microsoft-store.md
https://github.com/reactiveui/ReactiveUI/issues/1750
https://github.com/reactiveui/ReactiveUI/pull/1937
**Notes**
The .NET Native compilation issues appear to have been resolved via the above PR.
The "Windows Store" was also renamed to the "Microsoft Store" in 2017. Although the section should probably just be called "Universal Windows Platform / WinUI" now.
> Update Store name and remove old warning

- input/_Master.cshtml
Fixed a visual bug on our main page, which has lead to GitHub logo truncation:
This bug was reported in https://github.com/reactiveui/website/issues/394
**Notes**
It looks like this now:
> Fix GitHub logo truncation #394

- input/docs/resources/samples.md
Added the [Keyboard Switch](https://github.com/TolikPylypchuk/KeyboardSwitch) app, built with ReactiveUI and AvaloniaUI, to samples, as suggested by @worldbeater .
> Add Keyboard Switch as a sample app for AvaloniaUI

- input/assets/css/override.less
- input/docs/handbook/dependency-inversion/custom-dependency-inversion.md
After proofreading the DI docs one more time, noticed that we aren't showing how to use `Locator.SetLocator`, and are showing the code from the `Splat.Autofac` package instead. Assuming IoC container support packages are documented in https://github.com/reactiveui/splat#dependency-resolver-packages (and we are referencing that documentation page here https://www.reactiveui.net/docs/handbook/dependency-inversion/custom-dependency-inversion), probably worth showing how to implement a custom dependency resolver from scratch.
> Fix dependency resolver registration example

- input/docs/handbook/data-binding/avalonia.md
This PR improves Avalonia data binding documentation, adds a [super important note](https://github.com/reactiveui/website/issues/466) regarding a call to `.UseReactiveUI()`, and also mentions that AvaloniaUI support is provided directly by that team. Hopefully, this should make this documentation page a tiny bit more user-friendly.
> Improve Avalonia data binding docs

- input/docs/guidelines/debugging/disable-just-my-code.md
fixes #400 
I found the [original blog post](https://docs.microsoft.com/en-us/archive/blogs/davidklinems/how-to-stop-on-first-chance-exceptions-visual-studio-net-2003) (from 2005) but then was able to dig up a more up-to-date and elaborate version [here](https://devblogs.microsoft.com/devops/understanding-exceptions-while-debugging-with-visual-studio/) (2015).
> Fix the broken 'debugging tip' link

- input/docs/guidelines/platform/xamarin-android.md
- Use class/namespace names to display links (easier to browse).
- Reference the API namespace url instead of each individual class (less future maintenance required). The exception is the classes included in the core ReactiveUI project because those don't have a sub-namespace.
Broken links:
- https://reactiveui.net/api/reactiveui.android.support/reactiverecyclerviewadapter_1/
- https://reactiveui.net/api/reactiveui.androidsupport/reactiveactionbaractivity
- https://reactiveui.net/api/reactiveui/reactivefragmentactivity/	
- https://reactiveui.net/api/reactiveui/reactivelistadapter_1/	
- https://reactiveui.net/api/reactiveui/reactivepageradapter_1/
> Fix broken links and reference AndroidX

- input/docs/getting-started/compelling-example.md
The text describes OAPH on line 99, but never defines what it means. It is left to the user to figure that out. In most cases that is fine, however, I feel it is more clear if explicitly mentioned on line 87 before it is used. Especially helpful to people new to all this jargon.
> add a definition for OAPH before it is first used.

- input/docs/handbook/view-models/boilerplate-code.md
This PR documents a known ReactiveUI.Fody limitation related to C# auto property initializers. Based on a conversation in [Slack](http://reactiveui.net/slack).
> docs: Document the ReactiveUI.Fody Limitation

- input/_Master.cshtml
- input/assets/css/override.less
small ui fix
now navigation when hovering does not stick to the top block
> ui fix navigation

- input/docs/handbook/view-models/boilerplate-code.md
reactiveui/ReactiveUI#2416
Previous description makes it seem like non-generic types are impacted as well, which isn't true. This change clarifies the situation.
> 🦜 ReactiveUI.Fody property initializers limitation only applies to generic types

- input/docs/handbook/observable-as-property-helper/index.md
> fix: typo in OAPH documentation

- input/docs/handbook/routing/index.md
The link for the routing guide for AvaloniaUI was dead so I updated it to the new one.
> Updated AvaloniaUI routing guide link

- input/docs/handbook/logging/aspnet-logger.md
upda issue https://github.com/reactiveui/website/issues/594
> remove link (aspnet-logger.md)

- input/docs/handbook/routing/index.md
Use the correction from https://github.com/reactiveui/ReactiveUI/issues/2076#issuecomment-774244290
Now the code on the ReactiveUI [Routing](https://www.reactiveui.net/docs/handbook/routing/) documentation page behaves as the GIF image shows, the `RoutedViewHost` now goes back to the default content. Also, now you don't have to click the "Next page" button twice in order to enable the "Go back" button.
> fix: Correct Code Sample on the Routing Page

- input/docs/getting-started/installation/universal-windows-platform.md
We now have a `ReactiveUI.Uwp` package and the installation instructions are a bit misleading as they're not mentioning the new package:  https://www.reactiveui.net/docs/getting-started/installation/universal-windows-platform
If `ReactiveUI.Uwp` package isn't installed, the app crashes:
`System.ArgumentException: "Don't know how to detect when LoginApp.Uwp.Views.SignUpView is activated/deactivated, you may need to implement IActivationForViewFetcher"`
> fix: Update UWP installation instructions

- input/reactive-extensions/Using/Using.md
Fix for issue #776
**Notes**
Also tweaked formatting for references so that they are more distinct on the page
> Fixed broken links for 'Using Rx'

- input/contribute/compiling-reactive-ui/project-structure.md
Wrote documentation for all the packages in ReactiveUI and hyperlinked relevant resources on the Project Structure page at https://www.reactiveui.net/contribute/compiling-reactive-ui/project-structure
It seemed like the current Project Structure page was referring to old packages, so I thought it might be nice to update it with new packages and link to the relevant resources.
> Project Structure New Content

- input/docs/handbook/observable-as-property-helper/index.md
> Typo at a(n) invalid value

- reactiveui/docs/handbook/view-models/boilerplate-code.md
Added Source Generator usage
Related to #843
> Add Source Generators to boiler plate code
