src/reactiveui.net/Controllers/SlackController.cs
per #2 
this was an easy fix and the fix works as expected.
Submitted for review.
@ghuntley Thoughts?
Thanks.
=> fixed extraneous plus sign in email subject

src/reactiveui.net/Views/Concepts/Index.cshtml
Really nitpicky but I think this is a bit clearer wording wise.
=> Update Contents wording

input/docs/handbook/views/view-location.md
This commit shows how to work around certain problems that can occur when trying to work with ItemsControl and ReactiveUI.
Originally posted on StackOverflow (https://stackoverflow.com/q/45638376)
=> Added info on ItemTemplate hooking in ItemControl

input/contribute/developer-experience/help-wanted.md, input/contribute/developer-experience/index.cshtml, input/contribute/developer-experience/the-pitch.md, input/contribute/developer-experience/the-plan.md
I think this is the direction you want to go.
=> Added the-pitch.md, the-plan.md and help-wanted.md

input/index.cshtml
Mostly placeholder PR for discussion and work on the homepage.
Lots of the potential work resides in improving the brand identity of RxUI, showing developers that learning and using Rx will improve their productivity and help them make better products.
- e.g. Why does RxUI make dev work easier/better?
- Maybe this incorporates a "HelloReactiveUI" example app?
- Ideally could incorporate the existing "There is a better way" tagline.
- Is RxUI an MVVM Framework? Should we expect people to compare it to other MVVM frameworks, or is RxUI its own thing? How does RxUI differentiate itself from the others?
- Examples from other projects:
- "Learn once, write anywhere" - [MvvmCross](https://www.mvvmcross.com/) (probably not original)
- "Streams of values over time" - …
=> Homepage Improvements

input/contribute/developer-experience/the-pitch.md
@ghuntley I took a stab at reworking some of the verbiage on the page.  Feedback welcome!
This aligns to issue #22
=> [WIP] Update the-pitch.md

input/docs/handbook/OAPH/index.md
Use the abbreviation of ObservableAsPropertyHelper.
Closes #27
=> docs: OPAH to OAPH

input/index.cshtml
Correct "colleciton" to "collection".
=> Fix typo in homepage

input/_Footer.cshtml, input/assets/css/override.less
I've updated the footer design a little bit.
fixed the footer alignment bug. Looks a lot better now.
this should fix #15 
Had to do some hard testing on the site directly because wyam was failing on my mac with the following error:
```
The Mono runtime is not supported. Please check the GitHub repository and issue tracker for information on .NET Core support for cross platform execution.
An error occurred when executing task 'Build'.
Error: Wyam: Process returned an error (exit code 5)
```
Anyways, please provide feedback.
=> updated styles and fixed footer issues in mobile

input/assets/css/override.less
=> Added shadow to differentiate navigation menu from page in mobile view

input/docs/getting-started/index.md
=> Fixed spelling of "represent"

input/docs/handbook/testing/index.md
Building from a bit of discussion in Slack
https://reactivex.slack.com/archives/C02AJB872/p1507822824000243
=> add some details about testing

input/docs/thanks/index.cshtml
fixes https://github.com/reactiveui/ReactiveUI/issues/1501
:)
=> Add line to Thanks page

input/_Master.cshtml
Took a quick stab at this, if someone wants to help finish it off that would be A+.  What I'm after is the ability to define additional Wyam metadata on a per-page basis that when defined overrides/displays the value instead of the defaults.
=> make social metadata less annoying

.gitignore, build.cake
=> Update package dependencies to make local dev easier

input/_Navbar.cshtml
Tuples confused me, I think this is marginally clearer.
=> refactor navbar generation to use a dictionary

build.cake
Should we not download the artifacts in this stage and re-add the comment?
=> housekeeping: remove incorrect comment

config.wyam, input/_Infobar.cshtml
- overrides the infobar from https://github.com/Wyamio/Wyam/blob/master/themes/Docs/Samson/Shared/_Infobar.cshtml
=> adds 'Create Issue' link to Infobar (fixes #61)

input/_Master.cshtml
- "Malformed start tag. Attributes should be separated by whitespace."
I didn't modify the first line, not sure why that is showing up in the diff?  👎
=> Fix: Browser Error - HTML1423

input/docs/thanks/index.cshtml
- Change 'NoContainer' value to true
https://github.com/reactiveui/website/issues/86
=> Fix: Thanks page width issue

config.wyam, input/_Infobar.cshtml, input/assets/css/override.less
The form does a GET to google search scoped to reactiveui.net/docs/
Overrides the infobar from https://github.com/Wyamio/Wyam/blob/master/themes/Docs/Samson/Shared/_Infobar.cshtml
=> adds site search to docs (fixes #35)

input/assets/css/override.less, input/contribute/community/index.cshtml, input/docs/resources/videos.md
Possibly needs a bit of expansion, e.g. a mobile style/some tweaks, but I think this is a reasonable starting point.
=> set video widths with a class for consistency

input/docs/handbook/when-any/index.md
=> Fixed dead link to OAPH from When Any Value. (#92)

input/docs/handbook/view-models/index.md
Just a suggestion, since @ghuntley asked. It will take me a bit longer to add documentation to the empty view page as I need to align it with the example context of the rest of the documentation.
=> Add small clarification on the role of views

input/docs/samples/index.md
Maybe one would find that useful.
=> Add a reference to UWP sample app

input/docs/handbook/commands/combining-commands.md
Updated it so that it makes clear in what order the combined commands are executed. I was originally thinking it was sequential but checked the code first.
=> Updated combined commands documentation

input/contribute/features-and-patches/submitting-a-pull-request.md
We changed when we went to VSTS that pull requests should go through master. This fixes bug #123
=> Making the feature requests go through master

.vsts-ci.yml
=> Fix: the VSTS not correctly building the website.

input/blog/2018-08-07-reactiveui-v8.4.1-released.md
=> Added 2018-08-07-reacitveui-v8.4.1-released.md

input/docs/getting-started/installation/nuget-packages/index.md
Add info about `.UseReactiveUI()` AppBuilder extension.
=> Improve installation instructions for Avalonia

input/blog/2018-08-10-reactiveui-v8.5.1-released.md
@glennawatson blog post for the 8.5.1 release.
=> Added 2018-08-10-reactiveui-v8.5.1-released.md

input/blog/2018-08-13-deprecated-reactive-list.md
Added a blog post on the upcoming deprecation of Reactive List
=> Added 2018-08-13-deprecated-reactive-list.md

input/_Master.cshtml
=> Source font-awesome from cdnjs

input/blog/2018-08-14-reactiveui-v8.6.1-released.md
=> Added 2018-08-14-reactiveui-v8.6.1-released.md (#149)

.vsts-ci.yml, build.cmd, build.ps1, build.sh
The PR fixes https://github.com/reactiveui/website/issues/151 issue.
=> Fix "build.cmd -Target preview" command not working

input/docs/handbook/view-models/index.md
* Mentioned `PropertyChanged.Fody` and `ReactiveUI.Fody` packages
* Recommended always using `ReactiveObject` as a base class
* Updated code examples using new C# 7+ language features.
=> Update ViewModels page, add Fody

input/docs/handbook/when-activated/index.md
As you know, we should consider removing <a href="https://github.com/reactiveui/website/issues/139">all the chat logs from the docs</a> and changing them to proper documentation. So let's improve the `WhenActivated` page! :100:
=> Update WhenActivated page

input/assets/css/override.less
=> Fix css got broken by pull/178

input/_redirects
=> redirects to the correct license file

build.cake
This PR updates the site to Wyam 1.6.0. A small change with a big impact. Along with a more stable MSBuild integration, the update adds much better presentation of generic types and resolves several issues related to generic types.
=> Update to Wyam 1.6.0

input/docs/resources/samples.md
Moved Samples from the Documentation navigation to the Resources fly out menu.
=> Moved Samples to Resources Sub Menu (#194)

input/docs/handbook/events/index.md
Fixed too large iframe width on narrow screen devices, updated package names. Also removed a reference to a tweet posted by a renamed or deleted account (was unable to find out author's new nickname on Twitter) :(
=> Improve Events page

input/docs/handbook/data-binding/index.md, input/docs/handbook/data-binding/value-converters.md, input/docs/handbook/value-converters/index.md
Removed value converters page duplicate, referenced vlue converters page from data binding page, updated broken links, comments and code examples.
=> Improve value converters docs (#198)

input/docs/getting-started/installation/index.md
Added @worldbeater installation instructions to the installation page
=> housekeeping: Added installation matrix to the installation/index.md (#199)

input/docs/resources/samples.md
Among them are a great <a href="https://github.com/kondaskondas/FirstsStepsRUI">WPF routing example</a>, <a href="https://github.com/CodeHubApp/CodeHub">an extremely popular iOS GitHub client</a>, <a href="https://github.com/egramtel/egram.tel">an unofficial Telegram client built using Avalonia</a> and my <a href="https://github.com/worldbeater/ReactiveMvvm">cross platform app that uses PropertyChanged.Fody</a>.
=> Bring more good examples 👍

input/docs/getting-started/index.md
Reference new instalation page, fix broken links.
=> Improve getting started guide, fix broken links

input/assets/css/override.less
Closes https://github.com/reactiveui/website/issues/163
=> Fix incorrect menu behavior on narrow screens

input/docs/handbook/OAPH/index.md
I see folks [use old C# syntax](https://stackoverflow.com/questions/52950510/unit-testing-view-model-that-uses-selectmany-to-call-an-async-method-in-reactive) (`get { return }` instead of `=>`) for declaring `OAPH`s and their properties, so let's update the formatting on our website.
=> Improve OAPH page code formatting

input/docs/handbook/logging/index.md
Related to https://github.com/reactiveui/website/issues/139
=> Convert chat logs into docs for Logging page

input/docs/handbook/logging/index.md
=> Fix typo, prefer WhenAnyValue

input/docs/getting-started/index.md
See https://github.com/reactiveui/ReactiveUI/pull/1830
=> Use ReactiveWindow in the Getting Started app

input/docs/handbook/data-binding/avalonia.md, input/docs/handbook/data-binding/index.md
We've implemented that, let's document.
https://github.com/AvaloniaUI/Avalonia/pull/1951
https://github.com/AvaloniaUI/Avalonia/pull/1989
=> Add Avalonia IViewFor docs

input/blog/2018-11-07-reactive-command-abstract.md
Added a blog post on the removal of the ReactiveCommand abstract base class.
=> Added reactive-command-abstract.md

build.ps1, build.sh, tools/packages.config
This is to solve some nuget issues fixed in https://github.com/cake-build/cake/issues/2207
=> bump cake to version 0.30

input/docs/handbook/routing/index.md
Registering views manually can sometimes be painful. This PR adds a code example demonstrating the use of a custom `IViewLocator` implementation to the routing page.
=> Describe IViewLocator usage with routing

input/docs/handbook/testing/index.md
Tried to improve `ReactiveUI.Testing` docs, added info on injecting schedulers, etc.
=> Improve ReactiveUI.Testing docs

input/docs/handbook/testing/index.md
=> housekeeping: change testing example to use full ReactiveCommand.

input/docs/handbook/testing/index.md
IÄve added a call to `Subscribe()` in the unit test example and wrote an explanation.
Please have a look @glennawatson
=> Testing: Subscribe to executing command

input/docs/handbook/when-activated/index.md
Originally created by @cabauman
https://github.com/reactiveui/website/issues/191
=> Integrate ReactiveUI cheatsheet into WhenActivated page

input/docs/handbook/collections/index.md
=> Fix formatting issues, add change tracking notes

input/_Navbar.cshtml
More obvious for newbies where to ask for help, request features or help with development.
=> Mention Slack chat in NavBar

input/_Master.cshtml
-> 
Caused  by https://github.com/reactiveui/website/pull/241
=> Fix logo scale on mobile devices

input/docs/handbook/design-time/index.md
https://github.com/reactiveui/website/issues/139
=> Remove chat logs from DesignTime section

input/docs/handbook/data-persistence/index.md
Addresses https://github.com/reactiveui/website/issues/139
=> Improve Data Persistence docs

input/docs/handbook/data-binding/index.md
Closes https://github.com/reactiveui/website/issues/158
=> Clarify BindTo is one way

input/docs/getting-started/installation/index.md, input/docs/getting-started/upgrading.md, input/docs/getting-started/upgrading/index.md, input/docs/getting-started/upgrading/to-netstandard.md
Until we fix _ https://github.com/reactiveui/website/issues/247 let's do Ctrl+C/Ctrl+V :)
=> Update installation docs

build.cake
This updates the Debug target to work with the new Wyam .NET Core builds
=> Update Debug target

input/assets/css/bootstrap/variables.less, input/assets/css/override.less, input/docs/getting-started/installation/index.md
Update colors to be compatible with the new logo.
=> Update color palette

input/_Master.cshtml, input/assets/css/override.less, input/docs/getting-started/installation/index.md, input/docs/handbook/data-binding/avalonia.md, input/docs/handbook/data-binding/value-converters.md, input/docs/handbook/data-binding/windows-forms.md, input/docs/handbook/data-binding/windows-presentation-foundation.md, input/docs/handbook/data-binding/windows-store.md, input/docs/handbook/data-binding/xamarin-forms.md, input/docs/handbook/events/windows-forms.md, input/docs/handbook/scheduling/index.md
=> Minor tweaks, fix for #175

input/_Master.cshtml, input/assets/css/override.less, input/index.cshtml
=> Improve home page design

input/assets/css/override.less, input/index.cshtml
=> More home page improvements

input/docs/resources/samples.md
* Make titles clickable instead of using raw links
* Add an UWP sample app that uses `x:Bind` (seen questions about this in Slack)
=> Update samples page

input/docs/handbook/collections/index.md
* Describe how to work with immutable collections (`OAPH<T>`)
* Describe what `.ToCollection()` does (can bind to `OAPH<T>`)
* Describe how to `.Bind(out field)`
Based on questions folks ask at https://gitter.im/AvaloniaUI/Avalonia
=> Add Using DynamicData with ReactiveUI section

input/docs/handbook/when-activated/index.md
Mention how to trigger logic on view model deactivation, move credits to the bottom.
=> Improve WhenActivated

input/_Footer.cshtml, input/assets/css/override.less
=> Fix footer logo

input/docs/handbook/collections/index.md
Sample Filter()-Expressions use assigment instead of equality comparision.
=> fix incorrect sample code in index.md

input/docs/handbook/user-input-validation/index.md
Added ReactiveUI.Validation info in User Input Validation section.
=> Added ReactiveUI.Validation package info in User Input Validation section.

input/docs/handbook/user-input-validation/index.md
* Add NuGet package reference
* Add `ValidationRule` and `BindValidation` examples
* Add references to other great tools as FluentValidation and Sprache
=> Add more ReactiveUI.Validation docs

input/blog/2019-03-19-splat-v7.0.1-released.md
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Adds blog post on Splat v7 release
**What is the current behavior? (You can also link to an open issue here)**
No blog post exist outlining changes
**What is the new behavior (if this is a feature change)?**
A blog post serves as an artifact for people upgrading to find breaking changes.
Nothing.
=> Added 2019-03-19-splat-v7.0.1-released.md

input/contribute/developer-experience/the-plan.md
Corrected spelling and changed the word partical to particular
Doc update
Extension is spelled extnensions,
partical does not make sense in the context
extnensions is spelled now extension
partical is changed to particular, this is seems to make sense
Will not break the application
=> Spell Correction

input/docs/getting-started/minimum-versions.md
Add the minimum versions required by ReactiveUI.
=> Add minimum version documentation required by RxUI

input/_Sponsors.cshtml, input/docs/security/index.md, input/index.cshtml
Use newer OpenCollective svg, fix the missing tweet preventing the project from compilation.
Nothing.
=> Use newer OpenCollective svg, fix compilation

input/docs/handbook/user-input-validation/index.md
=> Word swap.

input/contribute/compiling-reactive-ui/index.md
doc update around an issue where not having .net core 3 can mean projects don't load in the solution.
=> compile page: add details on making sure you have the correct net core sdk

input/docs/getting-started/index.md
Docs update
We then `ObservableOn`.
We then `ObserveOn`.
Nothing, it's just an update of a code comment.
=> docs: fix typo in getting started code comment

input/docs/getting-started/installation/index.md
=> docs: sync with https://github.com/reactiveui/ReactiveUI/pull/2136

input/docs/guidelines/platform/uno-platform.md
docs: adds guidance for the uno platform
=> docs: added uno platform guidance

input/docs/handbook/view-models/index.md
Added verification for null in the .Select part of the WhenAnyValue
Bug fix
https://github.com/reactiveui/website/issues/351
Throws exception
Does not throw exception
=> Added handling of NullReferenceException

input/docs/handbook/interactions/index.md
Docs reading performance increased by at least 25%.
Degenerate verbosity.
Increased knowledge acquisition per word.
Existing records of speed reading.
According to one travel guide I read, there are 10,000 stray dogs roaming the streets of Sofia, Bulgaria. It's a cool place.
=> fewer words, same meaning

.github/pull_request_template.md
New simple PR template for docs PRs.
=> add new GH template for documentation PRs

input/docs/handbook/interactions/index.md
=> readability improvements

input/docs/handbook/routing/index.md
=> edit for readability

input/docs/handbook/commands/binding-commands.md
=> readability edits and some fixes

input/docs/handbook/routing/index.md
=> edits for readability

input/docs/handbook/routing/index.md
=> Fix broken link (#353)

input/docs/handbook/data-binding/value-converters.md
=> Fix broken GitHub link (#342)

input/docs/handbook/routing/index.md
=> Fix small typo

input/docs/handbook/scheduling/index.md
=> Fix some typo, wordings and styling

input/docs/upgrading/index.md
=> Update upgrading index.md

input/docs/handbook/collections/index.md
=> update with minor spelling error

input/_redirects
=> Re-enable Slack join link

input/docs/handbook/when-any/index.md, input/docs/upgrading/index.md
=> Fix invalid syntax and broken link

input/docs/handbook/user-input-validation/index.md
=> Update linke to Xamarin Blog

input/docs/handbook/data-binding/windows-presentation-foundation.md, input/docs/handbook/data-binding/windows-store.md, input/docs/handbook/data-binding/xamarin-forms.md, input/docs/handbook/observable-as-property-helper/index.md, input/docs/handbook/snippets/index.md
=> Fix data-binding and oaph code examples

input/docs/handbook/observable-as-property-helper/index.md
=> update observable-as-property-helper docs

input/docs/getting-started/index.md
Fixes for broken links introduced in PR #407
=> fix broken links in getting started docs

input/docs/getting-started/index.md
=> fix "compelling example" link

input/docs/handbook/data-binding/index.md
See Slack discussion - https://reactivex.slack.com/archives/C02AJB872/p1588067808227300
=> Document Subscribe vs Bind

input/docs/handbook/data-binding/xamarin-forms.md
=> Improve Xamarin Forms docs

build.cake, input/docs/handbook/observable-as-property-helper/index.md
=> Housekeeping: Add more reasoning for OAPH vs settable property.

input/docs/handbook/events/index.md
=> housekeeping: Change to mention Pharmacist

input/docs/resources/samples.md
Repo no longer exists anywhere I can find it.
=> Remove dead link.

input/docs/handbook/view-location/extending-iviewfor.md
Old links pointed to old branches. Scope of the first item also expanded beyond WinForms.
Headers tweaked to make it more clear that all of the following text only applies to Xamarin Forms.
=> Update links, add platform info, tweak headers.

input/2020-07-16-article-on-elevated-values.md, input/blog/2020-07-16-article-on-elevated-values.md
Updates article with feedback from @glennawatson that I'd forgotten to push /facepalm
=> add elevated values article

input/docs/resources/videos.md
=> added Xamarin .NET Conf talk

input/docs/handbook/view-models/boilerplate-code.md, input/docs/handbook/view-models/index.md
=> Improve ReactiveUI.Fody Documentation

input/_Master.cshtml, input/assets/css/override.less
This PR adds a banner with a reference to the [ReactiveUI Conference](https://www.rxuiconf.net/).
=> Reference RxUI Conference

input/docs/handbook/interactions/binding-interactions.md
This is short and to the point. It can be expanded later, but I wanted to at least get something up since that feature was already merged into main.
=> Add handbook page for Interaction Binding

input/docs/handbook/data-binding/index.md
=> Small update to databinding docs

input/docs/handbook/data-persistence/index.md
The `AutoSuspendHelper`-related APIs for Android changed a while ago (I think a long time ago indeed), so worth updating the samples on the data persistence documentation page. Also, this PR updates `NewtonsoftJsonSuspensionDriver` with an intension to improve developer experience (now the debugger won't break if that `FileNotFoundException` is thrown https://github.com/worldbeater/Camelotia/pull/39)
=> Update Code Samples on the Data Persistence Page

input/docs/handbook/collections/index.md
=> Add link to github repo in DynamicData docs

input/docs/handbook/data-persistence/index.md
This PR documents a new `AutoSuspendHelper` for `Xamarin.Forms` added in https://github.com/reactiveui/ReactiveUI/pull/2523
Additionally, this PR adds a reference to Avalonia `AutoSuspendHelper` [documentation page](http://avaloniaui.net/docs/reactiveui/suspension).
=> Document auto suspension on XF and Avalonia

input/_Master.cshtml
ReactiveUI Virtual Conference is over, so let's update the top banner text with a link to our YouTube channel with the recording.
=> Update the Conference Banner

input/docs/handbook/when-activated/index.md
Use the correct Link for IViewFor
=> Update link to the full IViewFor documentation

input/docs/guidelines/platform/windows-presentation-framework.md
resolves #382 
If this information is desired on other pages as well, just let me know and I'll update the PR. This just seemed like the most logical place, to me.
=> Document starting WPF app from another app

input/docs/getting-started/installation/avalonia.md
This adds @worldbeater  video on the introduction to Avalonia with ReactiveUI to the top of the article.
- [x ] New content
=> housekeeping: Add video to intro to avalonia with RxUI

build.cake
=> housekeeping: Add additional source libraries.

input/docs/handbook/user-input-validation/index.md
This PR adjusts ReactiveUI.Validation documentation as we have new and enhanced features in that library now. Also, we are now referencing ReactiveUI.Validation `README.md` file that contains most up-to-date documentation https://github.com/reactiveui/ReactiveUI.Validation/
=> docs: Update ReactiveUI.Validation Documentation

input/docs/getting-started/compelling-example.md
This fixes issue #497 and #501- a null reference exception which was causing the example to be... less compelling. Credit to @belliste and @Ydiren
What are the main goals of this change?
[x ] Content correction (accuracy, wrong information...)
Is this change related to any reported issue? (Optional)
reactiveui#497
reactiveui#501
Notes (Optional)
Just implemented the changes requested by users
=> Issue #501

input/docs/handbook/view-models/index.md
=> Remove a stray " in viewmodels handbook

input/_Scripts.cshtml, input/assets/css/override.less
fix issue https://github.com/reactiveui/website/issues/502
svg, unfortunately broken, replaced the icon with font Awesome
https://fontawesome.com/v4.7.0/icon/clipboard
after fix
=> fix copy button

input/docs/guidelines/debugging/debug-symbols.md
fix issue https://github.com/reactiveui/website/issues/511
=> fix debug-symbols.md video iframe

input/404.md
fix issue https://github.com/reactiveui/website/issues/513
=> update 404 page

input/reactive-extensions/Accept/Notification(T).Accept.md
fix issue https://github.com/reactiveui/website/issues/515
=> fix Notification(T).Accept.md output

input/assets/css/override.less
fix issue https://github.com/reactiveui/website/issues/519
after fix
=> fix menu on mobile

input/assets/css/override.less, input/blog/2018-05-01-reactiveui-v8.0.0-released.md, input/blog/2018-05-07-dotnet-core-3-and-reactiveui.md, input/contribute/community/index.cshtml, input/docs/getting-started/installation/avalonia.md, input/docs/guidelines/debugging/debug-symbols.md, input/docs/handbook/events/index.md, input/docs/handbook/when-any/index.md, input/docs/index.cshtml, input/docs/reactive-programming/videos.md, input/docs/resources/presentations.md, input/docs/resources/videos.md
update issue https://github.com/reactiveui/website/issues/523
**PC** 
**Mobile**
=> make all video responsive

input/_BlogPost.cshtml, input/assets/css/override.less
fix issue https://github.com/reactiveui/website/issues/525
after fix
=> fix share icons

input/docs/handbook/data-binding/xamarin-forms.md
=> Fixed typo

input/about/index.html, input/assets/img/favicons/browserconfig.xml, input/assets/img/favicons/manifest.json
=> update color for browsers

input/_Head.cshtml
relative PR https://github.com/reactiveui/website/pull/528
=> update theme on main site

input/assets/css/override.less
fix issue https://github.com/reactiveui/website/issues/532
after fix
=> fix anchor links

input/assets/css/override.less
fix issue https://github.com/reactiveui/website/issues/534
after fix:
main 
other pages
**menu scrollable**
=> fix navigation

input/assets/css/override.less
update issue https://github.com/reactiveui/website/issues/536
after:
=> update blog icons (ui)

input/assets/css/override.less
fis issue https://github.com/reactiveui/website/issues/538
after fix
=> update blog headers

input/assets/css/override.less
fix issue https://github.com/reactiveui/website/issues/545
=> remove the underline on hovering at anchors (ui)

input/_Scripts.cshtml
removed the anchor on the main page and on the blog pages and documentation remains the same
=> remove anchors from the main page

input/docs/handbook/view-models/index.md
=> fix: Don't repeat the same word twice

input/404.md, input/_Master.cshtml, input/assets/css/override.less
fix issue https://github.com/reactiveui/website/issues/549
=> centering content

input/assets/css/override.less
fix issue https://github.com/reactiveui/website/issues/552
=> remove expand underline (ui)

input/contribute/community/index.cshtml
issue https://github.com/reactiveui/website/issues/556
after update
=> update community page links

input/contribute/design/index.cshtml
fix issue https://github.com/reactiveui/website/issues/559
after update
=> update design page link

input/docs/resources/presentations.md
fix issue https://github.com/reactiveui/website/issues/561
=> add responsive video

input/_Footer.cshtml, input/contribute/index.md
update issue https://github.com/reactiveui/website/issues/563
=> add github discussions

input/_Navbar.cshtml
issue https://github.com/reactiveui/website/issues/565
=> rename slack chanel & add github discussions

input/assets/css/override.less
=> fix links on mobile

input/contribute/software-style-guide/code-style.md
fix issue https://github.com/reactiveui/website/issues/577
=> update relative link

input/assets/css/override.less
fix issue https://github.com/reactiveui/website/issues/581
after fix
=> fix table on mobile

input/docs/handbook/data-binding/value-converters.md
update issue https://github.com/reactiveui/website/issues/583
=> update BooleanToVisibilityTypeConverter link

input/docs/handbook/data-binding/windows-forms.md
update issue https://github.com/reactiveui/website/issues/586
=> update windows-forms.md link

input/assets/css/override.less
fix issue https://github.com/reactiveui/website/issues/588
=> fix table on lg screens

input/docs/handbook/events/index.md
fix issue https://github.com/reactiveui/website/issues/590
If there is a source somewhere I will replace, if not, then I will delete this line
=> remove meetup talk link

input/docs/handbook/events/windows-forms.md
update https://github.com/reactiveui/website/issues/592
=> update links (windows-forms.md)

input/docs/handbook/obsolete/collections/reactive-composite-collections/index.md
update issue https://github.com/reactiveui/website/issues/599
=> update reactive composite collections md links

input/docs/handbook/logging/index.md
=> housekeeping: extend logging page with splat bits

input/_Master.cshtml
fix issue https://github.com/reactiveui/website/issues/602
=> Accessibility - add lang to html tag

input/_Footer.cshtml, input/_Master.cshtml, input/index.cshtml
https://github.com/reactiveui/website/issues/604
=> Accessibility - add alt tag to logos

input/_Master.cshtml
https://github.com/reactiveui/website/issues/608
=> Accessibility - add title to button

input/_Infobar.cshtml
https://github.com/reactiveui/website/issues/610
=> Accessibility add title to search input

input/_Scripts.cshtml
https://github.com/reactiveui/website/issues/612
checked locally
=> Accessibility add title to all video iframe

input/_Scripts.cshtml
https://github.com/reactiveui/website/issues/614
=> Accessibility add title to search button

input/_Scripts.cshtml
https://github.com/reactiveui/website/issues/616
checked locally
=> add link name (accessibility)

input/docs/handbook/routing/index.md
https://github.com/reactiveui/website/issues/621
=> fix routing compelling example links

input/docs/handbook/view-models/index.md
upd https://github.com/reactiveui/website/issues/624
=> update view models link

input/_Scripts.cshtml
fix https://github.com/reactiveui/website/issues/627
=> Accessibility add button name to copy

input/docs/handbook/when-any/index.md
fix issue https://github.com/reactiveui/website/issues/629
I removed the link because this page does not exist
=> update commands link

input/docs/guidelines/debugging/disable-just-my-code.md
fix issue https://github.com/reactiveui/website/issues/631
=> update disable-just-my-code.md link

input/docs/guidelines/framework/command-execution.md
https://github.com/reactiveui/website/issues/637
=> update command-execution.md link

input/docs/guidelines/framework/dispose-your-subscriptions.md
fix issue https://github.com/reactiveui/website/issues/639
I commented out the broken link and updated another
=> update dispose-your-subscriptions.md link

input/docs/guidelines/platform/tizen.md
https://github.com/reactiveui/website/issues/641
& remove twitter link (not show content)
=> update tizen.md links

input/docs/guidelines/platform/windows-forms.md
https://github.com/reactiveui/website/issues/644
=> update windows-forms.md links

input/docs/guidelines/platform/windows-presentation-framework.md
update issue https://github.com/reactiveui/website/issues/649
=> update windows-presentation-framework.md links

input/docs/guidelines/platform/windows-universal-platform.md
https://github.com/reactiveui/website/issues/651
=> update windows-universal-platform.md links

input/docs/guidelines/platform/xamarin-android.md
https://github.com/reactiveui/website/issues/654
=> update xamarin-android.md links

input/docs/guidelines/platform/xamarin-forms.md
https://github.com/reactiveui/website/issues/656
=> update xamarin-forms.md links

input/docs/guidelines/platform/xamarin-ios.md
https://github.com/reactiveui/website/issues/658
=> update xamarin-ios.md links

input/docs/guidelines/platform/xamarin-mac.md
https://github.com/reactiveui/website/issues/660
=> update xamarin-mac.md links

input/docs/guidelines/platform/xamarin-mac.md
https://github.com/reactiveui/website/issues/660
=> update xamarin-mac.md link

input/docs/resources/videos.md
https://github.com/reactiveui/website/issues/663
=> update video.md link

input/blog/2020-07-10-article-on-reactive-programing.md
=> Fix indentation in a blog post's snippets.

input/docs/handbook/logging/index.md
https://github.com/reactiveui/website/issues/689
=> update logging links

input/docs/handbook/logging/observable-logger.md
https://github.com/reactiveui/website/issues/693
=> update observable logger link

input/blog/2013-03-12-reactiveui-v4.5.0-released.md
https://github.com/reactiveui/website/issues/697
=> update blog link

input/about/index.html
https://github.com/reactiveui/website/issues/700
=> update links about folder

input/docs/handbook/testing/index.md
https://github.com/reactiveui/website/issues/706
=> update links docs folder

input/index.cshtml
https://github.com/reactiveui/website/issues/708
=> update index links

input/_BlogPost.cshtml, input/dashboard/bower_components/icanhazjs/test/jquery-1.4.4.min.js, input/dashboard/bower_components/jquery-timeago/README.markdown, input/dashboard/bower_components/jquery-timeago/index.html, input/dashboard/bower_components/jquery-timeago/test/index.html, input/dashboard/bower_components/jquery/jquery.js, input/dashboard/bower_components/select2/README, input/dashboard/bower_components/underscore/CONTRIBUTING.md, input/dashboard/bower_components/underscore/README.md, input/dashboard/bower_components/underscore/docs/docco.css, input/dashboard/bower_components/underscore/docs/underscore.html, input/dashboard/bower_components/underscore/index.html, input/dashboard/bower_components/underscore/test/vendor/jquery.js, input/dashboard/bower_components/underscore/test/vendor/jslitmus.js, input/dashboard/bower_components/underscore/test/vendor/qunit.css, input/dashboard/bower_components/underscore/test/vendor/qunit.js, input/dashboard/bower_components/underscore/test/vendor/runner.js, input/dashboard/bower_components/underscore/underscore.js
https://github.com/reactiveui/website/issues/711
=> update input folder links

input/_Navbar.cshtml, input/assets/css/override.less
https://github.com/reactiveui/website/issues/713
=> update nav github icon to svg

input/_Footer.cshtml, input/assets/css/override.less
https://github.com/reactiveui/website/issues/715
=> update site padding on mobile (ui)

input/_Footer.cshtml
=> fix footer

input/_Navbar.cshtml
https://github.com/reactiveui/website/issues/721
=> Accessibility - update github link

input/code-of-conduct/index.md
https://github.com/reactiveui/website/issues/723
=> update code of conduct links

input/docs/resources/presentations.md
https://github.com/reactiveui/website/issues/729
=> update video iframe

input/docs/resources/presentations.md
https://github.com/reactiveui/website/issues/734
=> update iframe content

input/docs/getting-started/installation/index.md
This synchronizes installation instructions with [`README.md`](https://github.com/reactiveui/ReactiveUI). Currently, the [installation instructions](https://www.reactiveui.net/docs/getting-started/installation/) are a bit outdated, we aren't mentioning UWP, WinUI and MAUI on the website.
=> housekeeping: Mention more supported platforms

input/docs/handbook/when-any/index.md
Adds more notes about how the initial value is emitted
=> fix: add more description about

input/docs/handbook/commands/index.md
=> Fix typo: crush -> crash

input/docs/resources/videos.md
=> Add "Building Reactive UIs with Blazor" video

input/docs/resources/videos.md
=> Add all the videos from ReactiveUI YouTube channel.

input/docs/handbook/snippets/index.md
=> Update Visual Studio snippets guide

input/docs/handbook/observable-as-property-helper/index.md
=> FIX: propably copied typo from previous snippet

input/docs/guidelines/framework/performance-optimization.md
=> Add performance optimization guide.

input/docs/guidelines/platform/blazor.md
=> add information to Blazor guidlines

input/reactive-extensions/Creating/Creating.md
=> Fix URLs in Creating.md

input/_Master.cshtml
resolve https://github.com/reactiveui/website/issues/782
=> Accessibility fix navbar-collapse

input/_Master.cshtml
=> update collapse btn

input/docs/handbook/observable-as-property-helper/index.md
=> Typo at Observab(l)eAsPropertyHelper

.nuke/build.schema.json, reactiveui/docfx.json
ReactiveUI.Blend and ReactiveUI.Drawing incorrect Target for API
=> Fix - Update paths for API generation

reactiveui/docfx.json
resolve https://github.com/reactiveui/website/issues/804
=> Accessibility add lang tag to html

reactiveui/index.md
resolve https://github.com/reactiveui/website/issues/807
=> remove unnecessary header div

reactiveui/index.md
resolve https://github.com/reactiveui/website/issues/813
=> add more padding to home page (ui)

reactiveui/docs/getting-started/installation/windows-forms.md, reactiveui/docs/getting-started/installation/windows-presentation-foundation.md, reactiveui/docs/getting-started/minimum-versions.md, reactiveui/docs/guidelines/platform/windows-forms.md, reactiveui/docs/guidelines/platform/windows-presentation-framework.md
Add minimum TFM for WPF / WinForms to installation requirements
Update Android minimum version
N/A
=> Add minimum TFM for WPF / WinForms

reactiveui/template/layout/_master.tmpl, reactiveui/template/public/main.css
resolve https://github.com/reactiveui/website/issues/821
=> fix navigation on small screens

reactiveui/docs/handbook/commands/canceling.md
Change recommendations to use ReactiveCommand.CreateFromTask(async (ct) =>{}) of Observable.FromAsync(async (ct) =>{})
=> Update Cancellation to use a ReactiveCommand

reactiveui/docs/handbook/view-models/boilerplate-code.md
=> Fix typo in boilerplate-code.md

reactiveui/docs/handbook/view-models/boilerplate-code.md
=> Update for ReactiveUI.SourceGenerators V1.1.x

.github/workflows/main.yml, reactiveui/docs/handbook/commands/canceling.md
Cancellation => Cancelation
CancellableCommand  => CancelableCommand
closes #90 
=> Fix Cancelling to use Canceling

reactiveui/docs/handbook/data-persistence.md
No
Updated a URL in the data-persistence.md file
=> Updated url for AvaloniaUI's Data Persistence

reactiveui/template/layout/_master.tmpl
resolve https://github.com/reactiveui/website/issues/873
=> fix mobile ui

LICENSE, reactiveui/articles/2025-01-28-article-on-source-generators.md, reactiveui/articles/toc.yml, reactiveui/docs/handbook/view-models/boilerplate-code.md
Add article on ReactiveUI Source Generators
Update Boilerplate code to include partial property based Source Generators
=> Add ReactiveUI Source Generators Article

reactiveui/articles/2025-02-01-article-on-ReactiveUI-With-Wpf.md, reactiveui/articles/toc.yml, reactiveui/toc.yml
New Blog post on using ReactiveUI.Wpf
=> Add Blog Post for ReactiveUI.Wpf

reactiveui/Slack.md
https://github.com/reactiveui/ReactiveUI/pull/3985
Adds a https://reactiveui.net/slack url
=> Add Slack Redirect url

reactiveui/docs/handbook/collections.md, reactiveui/docs/handbook/data-binding/value-converters.md
=> Fix Typo and 404 - page not found

reactiveui/template/public/main.js
resolve https://github.com/reactiveui/website/issues/887
=> change twitter to x

reactiveui/template/public/main.js
resolve https://github.com/reactiveui/website/issues/889
=> fix X icon

reactiveui/template/public/main.js
resolve https://github.com/reactiveui/website/issues/891
=> update X icon

reactiveui/articles/2025-08-25-akavache_refreshed-V11.md, reactiveui/articles/toc.yml, reactiveui/toc.yml
Added a new article 'Akavache Refreshed' detailing the features and improvements in Akavache V11. 
Updated both articles/toc.yml and the main toc.yml to include and set the new article as the homepage for the Articles section.
=> Add Akavache Refreshed article
